version: "3"
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_container
    tty: true
    volumes:
      - ./frontend:/app/frontend
    # command: sh -c "cd /app/frontend && yarn install && yarn start"
    ports:
      - 3000:3000
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/app/backend
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    volumes:
      - react-nginx-go-mysql-todo:/var/lib/mysql
    ports:
      - 3306:3306
    links:
      - go
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "nginx_container"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - "go"
      - "node"
volumes:
  react-nginx-go-mysql-todo:
